### ISSUE TITLE
更新了ABP版本后 使用SMS功能JSON解析错误

### ISSUE THREAD

**Issue by slarkerino** [EasyAbp/Abp.TencentCloud#5]
在CommonRequest 类中SetRequestBody里的JSON操作无法正确解析数组撑Dictionary<string,string>。比如SMS里的电话号码数组一解析就会报错
![image](https://user-images.githubusercontent.com/7014849/123360515-07f65580-d5a0-11eb-9168-3b70764e3281.png)
![image](https://user-images.githubusercontent.com/7014849/123360748-6ae7ec80-d5a0-11eb-9eb0-9d71e3e9b086.png)

**Comment by real-zony** [comment]
Closed PR: https://github.com/EasyAbp/Abp.TencentCloud/pull/6
